//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface ViewController : UIViewController
{
}

- (void)didReceiveMemoryWarning;
- (void)sample;
- (void)seg1:(id)arg1 seg2:(unsigned long long)arg2;
- (void)viewDidLoad;
- (void)xxxxxx;
- (void)zheshi:(id)arg1 seg2:(unsigned long long)arg2;

@end

